// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ires_api.Data;

#nullable disable

namespace ires_api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230601033314_AddMaintenanceTable")]
    partial class AddMaintenanceTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ires_api.Models.AccountPayable", b =>
                {
                    b.Property<long>("chargeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("chargeid"));

                    b.Property<long>("accountid")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("actualdate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("companyid")
                        .HasColumnType("int");

                    b.Property<long>("createdbyid")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("datecreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateposted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateupdated")
                        .HasColumnType("datetime2");

                    b.Property<long>("expensetypeid")
                        .HasColumnType("bigint");

                    b.Property<string>("memo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("refno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("runningbalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<long>("updatedbyid")
                        .HasColumnType("bigint");

                    b.Property<long>("vendorid")
                        .HasColumnType("bigint");

                    b.HasKey("chargeid");

                    b.HasIndex("expensetypeid");

                    b.HasIndex("vendorid");

                    b.ToTable("expenseposting");
                });

            modelBuilder.Entity("ires_api.Models.Attachment", b =>
                {
                    b.Property<long>("documentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("documentid"));

                    b.Property<long>("attachedby")
                        .HasColumnType("bigint");

                    b.Property<int>("companyid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("dateattached")
                        .HasColumnType("datetime2");

                    b.Property<string>("documentname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("documenttypeid")
                        .HasColumnType("int");

                    b.Property<string>("filename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("filesize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("filetype")
                        .HasColumnType("int");

                    b.Property<long>("invoiceno")
                        .HasColumnType("bigint");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("bit");

                    b.Property<long>("lotid")
                        .HasColumnType("bigint");

                    b.Property<int>("typeid")
                        .HasColumnType("int");

                    b.HasKey("documentid");

                    b.ToTable("attachments");
                });

            modelBuilder.Entity("ires_api.Models.Bank", b =>
                {
                    b.Property<long>("bankid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("bankid"));

                    b.Property<int>("companyid")
                        .HasColumnType("int");

                    b.Property<bool>("isewallet")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("bankid");

                    b.ToTable("bank");
                });

            modelBuilder.Entity("ires_api.Models.BankAccount", b =>
                {
                    b.Property<long>("accountid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("accountid"));

                    b.Property<string>("accountname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accountno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("bankid")
                        .HasColumnType("bigint");

                    b.Property<string>("bankpreferredbranch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("companyid")
                        .HasColumnType("int");

                    b.Property<long>("createdbyid")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("datecreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isactive")
                        .HasColumnType("bit");

                    b.HasKey("accountid");

                    b.HasIndex("bankid");

                    b.ToTable("bankaccounts");
                });

            modelBuilder.Entity("ires_api.Models.BankTransfer", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("accountid")
                        .HasColumnType("bigint");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("bankid")
                        .HasColumnType("bigint");

                    b.Property<string>("memo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("paymentdate")
                        .HasColumnType("datetime2");

                    b.Property<long>("paymentid")
                        .HasColumnType("bigint");

                    b.Property<string>("refno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("bankid");

                    b.HasIndex("paymentid")
                        .IsUnique();

                    b.ToTable("banktobank");
                });

            modelBuilder.Entity("ires_api.Models.Bill", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("billdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("checkouturl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("companyid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("dateend")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("datefrom")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("duedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("particular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paymentid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paymentmode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paymentrefno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("bill");
                });

            modelBuilder.Entity("ires_api.Models.Booking", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("carid")
                        .HasColumnType("bigint");

                    b.Property<long>("clientid")
                        .HasColumnType("bigint");

                    b.Property<int>("companyid")
                        .HasColumnType("int");

                    b.Property<string>("drivername")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("enddate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isselfdrive")
                        .HasColumnType("bit");

                    b.Property<int>("noofdays")
                        .HasColumnType("int");

                    b.Property<decimal>("rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ratetype")
                        .HasColumnType("int");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("startdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<decimal>("totalrate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("carid");

                    b.HasIndex("clientid");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("ires_api.Models.Car", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<int>("companyid")
                        .HasColumnType("int");

                    b.Property<long>("createdbyid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("datecreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateupdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isactive")
                        .HasColumnType("bit");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("platenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("typeid")
                        .HasColumnType("int");

                    b.Property<long>("updatedbyid")
                        .HasColumnType("bigint");

                    b.Property<string>("year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("typeid");

                    b.ToTable("cars");
                });

            modelBuilder.Entity("ires_api.Models.CarMaintenance", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("carid")
                        .HasColumnType("bigint");

                    b.Property<int>("companyid")
                        .HasColumnType("int");

                    b.Property<long>("createdbyid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("datecreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateupdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("enddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("startdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("typeid")
                        .HasColumnType("int");

                    b.Property<long>("updatedbyid")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("carid");

                    b.HasIndex("typeid");

                    b.ToTable("carmaintenance");
                });

            modelBuilder.Entity("ires_api.Models.CarType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("isactive")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("cartypes");

                    b.HasData(
                        new
                        {
                            id = 1,
                            isactive = true,
                            name = "Hatchback"
                        },
                        new
                        {
                            id = 2,
                            isactive = true,
                            name = "Sedan"
                        },
                        new
                        {
                            id = 3,
                            isactive = true,
                            name = "Minivan"
                        },
                        new
                        {
                            id = 4,
                            isactive = true,
                            name = "Crossover"
                        },
                        new
                        {
                            id = 5,
                            isactive = true,
                            name = "Pickup"
                        },
                        new
                        {
                            id = 6,
                            isactive = true,
                            name = "SUV"
                        },
                        new
                        {
                            id = 7,
                            isactive = true,
                            name = "Van"
                        },
                        new
                        {
                            id = 8,
                            isactive = true,
                            name = "Others"
                        });
                });

            modelBuilder.Entity("ires_api.Models.CashDisbursement", b =>
                {
                    b.Property<long>("disbursementid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("disbursementid"));

                    b.Property<long>("accountid")
                        .HasColumnType("bigint");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("companyid")
                        .HasColumnType("int");

                    b.Property<long>("createdbyid")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("datecreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateupdated")
                        .HasColumnType("datetime2");

                    b.Property<long>("refaccountid")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("refdate")
                        .HasColumnType("datetime2");

                    b.Property<long>("refdisbursementid")
                        .HasColumnType("bigint");

                    b.Property<string>("refno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("transtype")
                        .HasColumnType("int");

                    b.Property<long>("updatedbyid")
                        .HasColumnType("bigint");

                    b.HasKey("disbursementid");

                    b.HasIndex("accountid");

                    b.HasIndex("refaccountid");

                    b.ToTable("pettycashdisbursement");
                });

            modelBuilder.Entity("ires_api.Models.Client", b =>
                {
                    b.Property<long>("custid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("custid"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("birthdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("companyid")
                        .HasColumnType("int");

                    b.Property<string>("contactno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("createdbyid")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("datecreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateupdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tinnumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("updatedbyid")
                        .HasColumnType("bigint");

                    b.HasKey("custid");

                    b.ToTable("customer");
                });

            modelBuilder.Entity("ires_api.Models.Company", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("billingcycle")
                        .HasColumnType("int");

                    b.Property<string>("contactno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isactive")
                        .HasColumnType("bit");

                    b.Property<bool?>("isverified")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("planid")
                        .HasColumnType("int");

                    b.Property<decimal>("storage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("subscriptionexpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("surveylimit")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("planid");

                    b.ToTable("company");
                });

            modelBuilder.Entity("ires_api.Models.Employee", b =>
                {
                    b.Property<long>("employeeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("employeeid"));

                    b.Property<int>("companyid")
                        .HasColumnType("int");

                    b.Property<long?>("createdbyid")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("datecreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isactive")
                        .HasColumnType("bit");

                    b.Property<bool?>("isappsysadmin")
                        .HasColumnType("bit");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middlename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobileno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwordresettoken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userpass")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("employeeid");

                    b.HasIndex("companyid");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("ires_api.Models.Expense", b =>
                {
                    b.Property<long>("expenseid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("expenseid"));

                    b.Property<long>("accountid")
                        .HasColumnType("bigint");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("companyid")
                        .HasColumnType("int");

                    b.Property<long>("createdbyid")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("dateupdated")
                        .HasColumnType("datetime2");

                    b.Property<long>("expensetypeid")
                        .HasColumnType("bigint")
                        .HasColumnName("expensetype");

                    b.Property<string>("memo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("payeeid")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("refdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("refno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("runningbalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("transdate")
                        .HasColumnType("datetime2");

                    b.Property<long>("transno")
                        .HasColumnType("bigint");

                    b.Property<long>("updatedbyid")
                        .HasColumnType("bigint");

                    b.Property<bool>("usepettycash")
                        .HasColumnType("bit");

                    b.HasKey("expenseid");

                    b.HasIndex("accountid");

                    b.HasIndex("expensetypeid");

                    b.HasIndex("payeeid");

                    b.ToTable("expenses");
                });

            modelBuilder.Entity("ires_api.Models.ExpenseType", b =>
                {
                    b.Property<long>("expensetypeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("expensetypeid"));

                    b.Property<int>("companyid")
                        .HasColumnType("int");

                    b.Property<long>("createdbyid")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("datecreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateupdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("expensetypecat")
                        .HasColumnType("int");

                    b.Property<string>("expensetypedesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isactive")
                        .HasColumnType("bit");

                    b.Property<long>("updatedbyid")
                        .HasColumnType("bigint");

                    b.HasKey("expensetypeid");

                    b.HasIndex("expensetypecat");

                    b.ToTable("expensetypes");
                });

            modelBuilder.Entity("ires_api.Models.ExpenseTypeCategory", b =>
                {
                    b.Property<int>("expensecatid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("expensecatid"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isactive")
                        .HasColumnType("bit");

                    b.HasKey("expensecatid");

                    b.ToTable("expensetypecategory");
                });

            modelBuilder.Entity("ires_api.Models.Log", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<int>("companyid")
                        .HasColumnType("int");

                    b.Property<long>("employeeid")
                        .HasColumnType("bigint");

                    b.Property<string>("logAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("logdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("logtitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("moduleid")
                        .HasColumnType("int");

                    b.Property<int>("withadmin")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("logs");
                });

            modelBuilder.Entity("ires_api.Models.Lot", b =>
                {
                    b.Property<long>("lot_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("lot_id"));

                    b.Property<decimal>("area")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("blockno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("blocknoint")
                        .HasColumnType("int");

                    b.Property<decimal>("comatdown")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("commissionableamount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("compercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("default_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("housearea")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("isactive")
                        .HasColumnType("bit");

                    b.Property<string>("lotno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("lotnoint")
                        .HasColumnType("int");

                    b.Property<decimal>("min_down")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("parkingarea")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("pricepersquare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("propertyid")
                        .HasColumnType("bigint");

                    b.Property<string>("titleno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("lot_id");

                    b.ToTable("lot");
                });

            modelBuilder.Entity("ires_api.Models.MaintenanceType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("isactive")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("id");

                    b.ToTable("maintenancetypes");

                    b.HasData(
                        new
                        {
                            id = 1,
                            isactive = true,
                            name = "Repair and Maintenance"
                        },
                        new
                        {
                            id = 2,
                            isactive = true,
                            name = "Registration Renewal"
                        },
                        new
                        {
                            id = 3,
                            isactive = true,
                            name = "Personal Use"
                        },
                        new
                        {
                            id = 4,
                            isactive = true,
                            name = "Others"
                        });
                });

            modelBuilder.Entity("ires_api.Models.Module", b =>
                {
                    b.Property<int>("moduleid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("moduleid"));

                    b.Property<bool>("isactive")
                        .HasColumnType("bit");

                    b.Property<string>("modulename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("moduletypeid")
                        .HasColumnType("int");

                    b.HasKey("moduleid");

                    b.ToTable("applicationmodules");
                });

            modelBuilder.Entity("ires_api.Models.Notification", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("datecreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("employeeid")
                        .HasColumnType("bigint");

                    b.Property<bool>("isread")
                        .HasColumnType("bit");

                    b.Property<int>("typeid")
                        .HasColumnType("int");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("ires_api.Models.Office", b =>
                {
                    b.Property<long>("accountid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("accountid"));

                    b.Property<string>("accountname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("companyid")
                        .HasColumnType("int");

                    b.Property<long>("createdbyid")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("datecreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateupdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isactive")
                        .HasColumnType("bit");

                    b.Property<string>("memo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("pettycashbalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("updatedbyid")
                        .HasColumnType("bigint");

                    b.HasKey("accountid");

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("ires_api.Models.OtherCharge", b =>
                {
                    b.Property<long>("chargeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("chargeid"));

                    b.Property<decimal>("balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("chargeamount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("chargedate")
                        .HasColumnType("datetime2");

                    b.Property<long>("chargetype")
                        .HasColumnType("bigint");

                    b.Property<decimal>("interestamount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("interestpercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("interestype")
                        .HasColumnType("int");

                    b.Property<long>("invoiceno")
                        .HasColumnType("bigint");

                    b.Property<long>("lotid")
                        .HasColumnType("bigint");

                    b.Property<decimal>("runningbalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("surveyid")
                        .HasColumnType("bigint");

                    b.HasKey("chargeid");

                    b.HasIndex("chargetype");

                    b.HasIndex("surveyid");

                    b.ToTable("othercharges");
                });

            modelBuilder.Entity("ires_api.Models.OtherFee", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<long?>("createdby")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("datecreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateupdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isactive")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("updatedbyid")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("otherfees");
                });

            modelBuilder.Entity("ires_api.Models.Payment", b =>
                {
                    b.Property<long>("paymentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("paymentid"));

                    b.Property<decimal>("change")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("companyid")
                        .HasColumnType("int");

                    b.Property<long>("custid")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("datecreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("daterefunded")
                        .HasColumnType("datetime2");

                    b.Property<long>("encodedby")
                        .HasColumnType("bigint");

                    b.Property<long>("orno")
                        .HasColumnType("bigint");

                    b.Property<string>("paidby")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("paymentdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("paymentmode")
                        .HasColumnType("int");

                    b.Property<string>("receiptno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("receipttype")
                        .HasColumnType("int");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("replacedreceipts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("replacementpaymentid")
                        .HasColumnType("bigint");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<decimal>("tender")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("totalamount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("transtype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("paymentid");

                    b.HasIndex("custid");

                    b.HasIndex("encodedby");

                    b.ToTable("payment");
                });

            modelBuilder.Entity("ires_api.Models.PaymentCheck", b =>
                {
                    b.Property<long>("checkid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("checkid"));

                    b.Property<string>("accountnumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("bankid")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("checkdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("checkno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("datedeposited")
                        .HasColumnType("datetime2");

                    b.Property<long>("depositaccount")
                        .HasColumnType("bigint");

                    b.Property<string>("memo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("paymentid")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("replacedcheckdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("replacedcheckno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("checkid");

                    b.HasIndex("bankid");

                    b.HasIndex("paymentid")
                        .IsUnique();

                    b.ToTable("checks");
                });

            modelBuilder.Entity("ires_api.Models.PaymentDetail", b =>
                {
                    b.Property<long>("paymentdetailid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("paymentdetailid"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("chargeid")
                        .HasColumnType("bigint");

                    b.Property<long>("defaultchargeid")
                        .HasColumnType("bigint");

                    b.Property<decimal>("discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("discount_type")
                        .HasColumnType("bigint");

                    b.Property<long>("invoiceno")
                        .HasColumnType("bigint");

                    b.Property<long>("lotid")
                        .HasColumnType("bigint");

                    b.Property<long>("otherfeeid")
                        .HasColumnType("bigint");

                    b.Property<int>("payableType")
                        .HasColumnType("int");

                    b.Property<long>("paymentid")
                        .HasColumnType("bigint");

                    b.Property<long>("paymenttype")
                        .HasColumnType("bigint");

                    b.Property<string>("remarks_deletion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("rentalchargeid")
                        .HasColumnType("bigint");

                    b.Property<long>("rentalid")
                        .HasColumnType("bigint");

                    b.Property<decimal>("runningbalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("surveyid")
                        .HasColumnType("bigint");

                    b.HasKey("paymentdetailid");

                    b.HasIndex("paymentid");

                    b.ToTable("paymentdetails");
                });

            modelBuilder.Entity("ires_api.Models.PlanModule", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<bool>("isactive")
                        .HasColumnType("bit");

                    b.Property<int>("moduleid")
                        .HasColumnType("int");

                    b.Property<int>("planid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("moduleid");

                    b.ToTable("planmodules");
                });

            modelBuilder.Entity("ires_api.Models.Project", b =>
                {
                    b.Property<long>("propertyid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("propertyid"));

                    b.Property<decimal>("addoninterestpermonth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("alias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("allow_straight_monthly")
                        .HasColumnType("int");

                    b.Property<decimal>("area")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("com_percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("commissionterm")
                        .HasColumnType("int");

                    b.Property<int>("companyid")
                        .HasColumnType("int");

                    b.Property<decimal>("compercentageoverterm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("computationtype")
                        .HasColumnType("int");

                    b.Property<decimal>("defaultcommission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("interest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("interesttype")
                        .HasColumnType("int");

                    b.Property<int>("paymentextension")
                        .HasColumnType("int");

                    b.Property<int>("paymentterm")
                        .HasColumnType("int");

                    b.Property<string>("propertyname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("withholding")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("propertyid");

                    b.ToTable("property");
                });

            modelBuilder.Entity("ires_api.Models.RentalProperty", b =>
                {
                    b.Property<long>("propertyid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("propertyid"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("alias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contactno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("monthlyrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("projectid")
                        .HasColumnType("bigint");

                    b.Property<string>("propertyname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("propertyid");

                    b.HasIndex("projectid");

                    b.ToTable("propertyrentals");
                });

            modelBuilder.Entity("ires_api.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isactive")
                        .HasColumnType("bit");

                    b.Property<int>("moduleid")
                        .HasColumnType("int");

                    b.Property<decimal>("monthlysubscription")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("storage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("surveylimit")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("subscriptionplan");
                });

            modelBuilder.Entity("ires_api.Models.Survey", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("companyid")
                        .HasColumnType("int");

                    b.Property<decimal>("contractprice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("createdbyid")
                        .HasColumnType("bigint");

                    b.Property<long>("custid")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("datecreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateupdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("propertyname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("surveydate")
                        .HasColumnType("datetime2");

                    b.Property<string>("surveyno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titleno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("updatedbyid")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("custid");

                    b.ToTable("survey");
                });

            modelBuilder.Entity("ires_api.Models.UserPrivilege", b =>
                {
                    b.Property<long>("userprivid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("userprivid"));

                    b.Property<bool>("canaccess")
                        .HasColumnType("bit");

                    b.Property<bool>("canadd")
                        .HasColumnType("bit");

                    b.Property<bool>("canedit")
                        .HasColumnType("bit");

                    b.Property<bool>("canverify")
                        .HasColumnType("bit");

                    b.Property<bool>("canview")
                        .HasColumnType("bit");

                    b.Property<bool>("canvoid")
                        .HasColumnType("bit");

                    b.Property<long>("createdbyid")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("datecreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("moduleid")
                        .HasColumnType("int");

                    b.Property<long>("userid")
                        .HasColumnType("bigint");

                    b.HasKey("userprivid");

                    b.HasIndex("moduleid");

                    b.ToTable("userprivileges");
                });

            modelBuilder.Entity("ires_api.Models.Vendor", b =>
                {
                    b.Property<long>("vendorid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("vendorid"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("companyid")
                        .HasColumnType("int");

                    b.Property<string>("contactno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("createdbyid")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("datecreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateupdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isactive")
                        .HasColumnType("bit");

                    b.Property<string>("tinno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("updatedbyid")
                        .HasColumnType("bigint");

                    b.Property<string>("vendorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("vendorid");

                    b.ToTable("vendors");
                });

            modelBuilder.Entity("ires_api.Models.AccountPayable", b =>
                {
                    b.HasOne("ires_api.Models.ExpenseType", "expenseType")
                        .WithMany()
                        .HasForeignKey("expensetypeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ires_api.Models.Vendor", "vendor")
                        .WithMany()
                        .HasForeignKey("vendorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("expenseType");

                    b.Navigation("vendor");
                });

            modelBuilder.Entity("ires_api.Models.BankAccount", b =>
                {
                    b.HasOne("ires_api.Models.Bank", "bank")
                        .WithMany("bankAccounts")
                        .HasForeignKey("bankid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bank");
                });

            modelBuilder.Entity("ires_api.Models.BankTransfer", b =>
                {
                    b.HasOne("ires_api.Models.Bank", "bank")
                        .WithMany("bankTransfers")
                        .HasForeignKey("bankid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ires_api.Models.Payment", "payment")
                        .WithOne("bankTransfer")
                        .HasForeignKey("ires_api.Models.BankTransfer", "paymentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bank");

                    b.Navigation("payment");
                });

            modelBuilder.Entity("ires_api.Models.Booking", b =>
                {
                    b.HasOne("ires_api.Models.Car", "car")
                        .WithMany()
                        .HasForeignKey("carid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ires_api.Models.Client", "client")
                        .WithMany()
                        .HasForeignKey("clientid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("car");

                    b.Navigation("client");
                });

            modelBuilder.Entity("ires_api.Models.Car", b =>
                {
                    b.HasOne("ires_api.Models.CarType", "carType")
                        .WithMany()
                        .HasForeignKey("typeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("carType");
                });

            modelBuilder.Entity("ires_api.Models.CarMaintenance", b =>
                {
                    b.HasOne("ires_api.Models.Car", "car")
                        .WithMany()
                        .HasForeignKey("carid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ires_api.Models.MaintenanceType", "maintenanceType")
                        .WithMany()
                        .HasForeignKey("typeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("car");

                    b.Navigation("maintenanceType");
                });

            modelBuilder.Entity("ires_api.Models.CashDisbursement", b =>
                {
                    b.HasOne("ires_api.Models.Office", "office")
                        .WithMany()
                        .HasForeignKey("accountid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ires_api.Models.Office", "refOffice")
                        .WithMany()
                        .HasForeignKey("refaccountid");

                    b.Navigation("office");

                    b.Navigation("refOffice");
                });

            modelBuilder.Entity("ires_api.Models.Company", b =>
                {
                    b.HasOne("ires_api.Models.SubscriptionPlan", "subscriptionPlan")
                        .WithMany("companies")
                        .HasForeignKey("planid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("subscriptionPlan");
                });

            modelBuilder.Entity("ires_api.Models.Employee", b =>
                {
                    b.HasOne("ires_api.Models.Company", "company")
                        .WithMany("employees")
                        .HasForeignKey("companyid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("company");
                });

            modelBuilder.Entity("ires_api.Models.Expense", b =>
                {
                    b.HasOne("ires_api.Models.Office", "office")
                        .WithMany()
                        .HasForeignKey("accountid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ires_api.Models.ExpenseType", "expenseType")
                        .WithMany()
                        .HasForeignKey("expensetypeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ires_api.Models.Vendor", "vendor")
                        .WithMany()
                        .HasForeignKey("payeeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("expenseType");

                    b.Navigation("office");

                    b.Navigation("vendor");
                });

            modelBuilder.Entity("ires_api.Models.ExpenseType", b =>
                {
                    b.HasOne("ires_api.Models.ExpenseTypeCategory", "category")
                        .WithMany("expenseTypes")
                        .HasForeignKey("expensetypecat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("ires_api.Models.OtherCharge", b =>
                {
                    b.HasOne("ires_api.Models.OtherFee", "fee")
                        .WithMany("otherCharges")
                        .HasForeignKey("chargetype")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ires_api.Models.Survey", "survey")
                        .WithMany("otherCharges")
                        .HasForeignKey("surveyid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fee");

                    b.Navigation("survey");
                });

            modelBuilder.Entity("ires_api.Models.Payment", b =>
                {
                    b.HasOne("ires_api.Models.Client", "client")
                        .WithMany("payments")
                        .HasForeignKey("custid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ires_api.Models.Employee", "createdBy")
                        .WithMany("encodedPayments")
                        .HasForeignKey("encodedby")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("client");

                    b.Navigation("createdBy");
                });

            modelBuilder.Entity("ires_api.Models.PaymentCheck", b =>
                {
                    b.HasOne("ires_api.Models.Bank", "bank")
                        .WithMany("checks")
                        .HasForeignKey("bankid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ires_api.Models.Payment", "payment")
                        .WithOne("paymentCheck")
                        .HasForeignKey("ires_api.Models.PaymentCheck", "paymentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bank");

                    b.Navigation("payment");
                });

            modelBuilder.Entity("ires_api.Models.PaymentDetail", b =>
                {
                    b.HasOne("ires_api.Models.Payment", "payment")
                        .WithMany("paymentDetails")
                        .HasForeignKey("paymentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("payment");
                });

            modelBuilder.Entity("ires_api.Models.PlanModule", b =>
                {
                    b.HasOne("ires_api.Models.Module", "module")
                        .WithMany()
                        .HasForeignKey("moduleid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("module");
                });

            modelBuilder.Entity("ires_api.Models.RentalProperty", b =>
                {
                    b.HasOne("ires_api.Models.Project", "project")
                        .WithMany("rentalProperties")
                        .HasForeignKey("projectid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("project");
                });

            modelBuilder.Entity("ires_api.Models.Survey", b =>
                {
                    b.HasOne("ires_api.Models.Client", "client")
                        .WithMany("surveys")
                        .HasForeignKey("custid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("client");
                });

            modelBuilder.Entity("ires_api.Models.UserPrivilege", b =>
                {
                    b.HasOne("ires_api.Models.Module", "module")
                        .WithMany()
                        .HasForeignKey("moduleid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("module");
                });

            modelBuilder.Entity("ires_api.Models.Bank", b =>
                {
                    b.Navigation("bankAccounts");

                    b.Navigation("bankTransfers");

                    b.Navigation("checks");
                });

            modelBuilder.Entity("ires_api.Models.Client", b =>
                {
                    b.Navigation("payments");

                    b.Navigation("surveys");
                });

            modelBuilder.Entity("ires_api.Models.Company", b =>
                {
                    b.Navigation("employees");
                });

            modelBuilder.Entity("ires_api.Models.Employee", b =>
                {
                    b.Navigation("encodedPayments");
                });

            modelBuilder.Entity("ires_api.Models.ExpenseTypeCategory", b =>
                {
                    b.Navigation("expenseTypes");
                });

            modelBuilder.Entity("ires_api.Models.OtherFee", b =>
                {
                    b.Navigation("otherCharges");
                });

            modelBuilder.Entity("ires_api.Models.Payment", b =>
                {
                    b.Navigation("bankTransfer");

                    b.Navigation("paymentCheck");

                    b.Navigation("paymentDetails");
                });

            modelBuilder.Entity("ires_api.Models.Project", b =>
                {
                    b.Navigation("rentalProperties");
                });

            modelBuilder.Entity("ires_api.Models.SubscriptionPlan", b =>
                {
                    b.Navigation("companies");
                });

            modelBuilder.Entity("ires_api.Models.Survey", b =>
                {
                    b.Navigation("otherCharges");
                });
#pragma warning restore 612, 618
        }
    }
}
